Capstone.Web/Controllers/PotholeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Capstone.Web.Models;
using Capstone.Web.DAL;

namespace Capstone.Web.Controllers
{
    public class PotholeController : Controller
    {
        private const string UsernameKey = "Pothole_UserName";

        public User CurrentUser
        {
            get
            {
                if (IsAuthenticated)
                {
                    return (User)Session["user"];
                }

                return null;
            }
        }

        public bool IsAuthenticated
        {
            get
            {
                return Session["user"] != null;
            }
        }

       /* public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }
        */

        [ChildActionOnly]
        public ActionResult GetNavbar()
        {
            User model = (User)Session["user"];

            return PartialView("_Navbar", model);
        }

    }
}

Capstone.Web/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootswatch.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/creative.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Pothole Tracker</a>
            </div>
            @Html.Action("GetNavbar", "Pothole")
        </div>
    </nav>

    @RenderBody()

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAPiyVpokXSqtRW8T58W_gFi9YutxN-ZlA&callback=initMap"></script>

</body>
</html>

Capstone.Web/Views/Shared/_Navbar.cshtml
@{
    Layout = null;
}
@model Capstone.Web.Models.User
@using Capstone.Web.Extensions

@if (Model == null)//there is no user logged in
{

    <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
            <li><a href="/home/index">Home</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="/user/register"><span class="glyphicon glyphicon-user"></span> Register </a></li>
            <li><a href="/user/login"><span class="glyphicon glyphicon-log-in"></span> Login </a></li>
        </ul>
    </div>
}
else if(Model.UserType == "r") // A user is logged in
{
    <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
            <li><a href="/home/index">Home</a></li>
            <li><a href="/function/report">Report Pothole</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="navbar-text">Welcome @Model.Name.Split(' ')[0]</li>
            <li><a href="/user/logout"><span class="glyphicon glyphicon-log-out"></span> Log Out </a></li>
        </ul>
    </div>
}
else if (Model.UserType == "e") // A user is logged in
{
    <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
            <li><a href="/home/index">Home</a></li>
            <li><a href="/function/report">Report Pothole</a></li>
            @*<li><a href="/function/review">Employee Portal</a></li>*@
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown">Employee Portal<span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href='/function/review/?option=all'>All Potholes</a></li>
                    <li><a href='/function/review/?option=uninspected'>Awaiting Inspection</a></li>
                    <li><a href='/function/review/?option=inspected'>Awaiting Repair</a></li>
                    <li><a href='/function/review/?option=inRepair'>Repair in Progress</a></li>
                    <li><a href='/function/review/?option=complete'>Repair Completed</a></li>
                </ul>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="navbar-text">Welcome @Model.Name.Split(' ')[0]</li>
            <li><a href="/user/logout"><span class="glyphicon glyphicon-log-out"></span> Log Out </a></li>
        </ul>
    </div>
}